### PR TITLE
New output function: range of time steps

### PR DESCRIPTION
**Pull request by jvollhueter**
A new tag in the xml file can be used to specify an interval of time steps in which output should be written. The synthax with ':' (e.g. [5:8] or [:8]) was unfortunately not so easy to implement. Because of the less complex variant for people who have no idea about indexing in programming languages the syntax for the new tag is:
<output_time_range> [<start_time>, <end_time>] </output_time_range>.

### CODE REVIEW

**Comment by jvollhueter** [comment]
Update of doc still missing - I will do when the final implementation is fixed.

**Review by mcwimm — CHANGES_REQUESTED** [review]
It works. However, I have 2 issues:
1) error handling (see suggestion)
2) the use of this tag makes all other obsolete (e.g., every_n_timestep). It would be useful to use combinations of them

**Comment by jvollhueter** [comment]
> It works. However, I have 2 issues:
> 
>     2. the use of this tag makes all other obsolete (e.g., every_n_timestep). It would be useful to use combinations of them

2: At the moment the user could let write the output e.g. every 20th timestep before the range she or he is actually interested. So the user has an overview how the population has developed until the important interval begins. Maybe that's a good option to check whether everything is ok. If everything works like I wanted it to every three output options could be used parallel

**Review by mcwimm — APPROVED** [review]

**Comment by mcwimm** [comment]
@jvollhueter can you please test it again and feel free to continue/revise the documentation.

**Pull request merged**
